### ISSUE TITLE
Alternate stages

### ISSUE THREAD

**Issue by UieSolverofThings** [TheOriginalSINe/Project-M-CC#57] opened 2015-12-06 10:10 UTC
Four stages got new alternate variants in 3.61

They weren't assigned to any button commands though, so I fixed that.

It feels relatively harmless to include given it only adds and doesn't replace or take away anything that was already there.

The alternate stages are

Luigi's Mansion
Dracula's Castle (assigned to L)

Pokemon Stadium 2
3.02 (assigned to Z)

Bowser's Castle
Peach's Castle Melee (assigned to Z)

Norfair has two alts that seem to be slightly different variants of what's already there. I assigned them to Z and Y respectively, but I've tested them both and at first glance they just seem like the same as the default two alternates we have already. Doesn't break anything though, so I thought I'd include them in-case someone does find out what's different.

https://dl.dropboxusercontent.com/u/180104980/RSBE01.gct

This is all you need to activate the alts

Sorry if I did something wrong, I'm new to Github.

**Comment by jojmaht** [comment] 2015-12-06 12:20
Ideally it'd be better to do it as a pull request but I'll do it for you.

**Comment by ghost** [comment] 2015-12-06 18:04
Would you mind making a few pull requests for some fixes that i've made?

**Comment by jojmaht** [comment] 2015-12-06 18:12
@Rage17 Sure, what kind of changes?

**Comment by ghost** [comment] 2015-12-06 18:14
Knuckles taunts, win animations, and Super Knuckles. Also Snake's cardboard box goodies.

**Comment by ghost** [comment] 2015-12-06 18:15
TheOriginalSINe asked about where the Knuckles animations came from, and I told them that the original PSA's makers have since left Brawl modding.

**Comment by jojmaht** [comment] 2015-12-06 18:16
Upload it in a nice big package, I'll organize it all then.

**Comment by ghost** [comment] 2015-12-06 18:17
Gotcha. Thanks, by the way.

**Comment by ghost** [comment] 2015-12-06 18:21
For some reason, GitHub isn't recognizing the zip I made as a zip(I made it with 7zip, if that matters). Anyways, here's the stuff: https://www.cubbyusercontent.com/pli/PMDevBuildFixesV1.zip/_04ef1e3e00d74c15aaf4f553f1a5ecb0

**Comment by UieSolverofThings** [comment] 2015-12-06 18:33
Oh, on the topic of Snake's taunt goodies, I'm currently trying to find a way to make the Shiny pokemon sparkle on entrance again like they do in 3.61

**Comment by ghost** [comment] 2015-12-06 18:34
They did that? Nice find!

**Comment by UieSolverofThings** [comment] 2015-12-06 18:48
Yup! I'll see if I can get a picture of it. It was an effect exclusive to the shiny alt colors (and I think the golden armor Mewtwo too)

**Comment by ghost** [comment] 2015-12-06 18:56
I heard that the FitMotionEtc.pac had the sparkles, so maybe we could use those

**Comment by ghost** [comment] 2015-12-06 19:01
The sparkles seem to be GFX calls in the moveset file, rather than an actual model.

**Comment by ewmb7701** [comment] 2015-12-06 20:38
Alright I merged the pull request. Now all we need to do is update the Stage Select Screen preview.

**Comment by ewmb7701** [comment] 2015-12-07 17:40
I had to redo the codeset and the text codeset for this. But it's done and pushed, so I'm closing it now.

**Comment by JCOnyx** [comment] 2015-12-07 18:19
Personally, I don't quite understand why 3.02 PS2 would be necessary to include.  I'll also take a look over the Norfair alts and see if they had any platform movement changes or boundary changes, but I also don't see why we'd need to include them regardless.

Those specifically seem to be counteractive to preserving the 3.6 meta since they are sometimes used in competitive play, and they're secret alts on top of that as well.  I don't know, just doesn't seem right to include them.

**Comment by ewmb7701** [comment] 2015-12-07 18:23
I agree that it is quite strange. However, PS2 is kind of fun to play casually, as are Melee Peach's Castle. I know one of the Norfair alts has a secondary "main" platform that goes above the two sub platforms. I personally like the platforms, and I want to test it with friends before making any decisions. However, including Dracula's Castle does present a bit of a legal and aesthetic issue. Castlevania wasn't in Brawl at all, so there's definitely licensing issues. 

Also I'm reopening the issue, because there is more to be discussed.

**Comment by bb010g** [comment] 2015-12-07 19:16
Dracula's doesn't have much over Delfino's Secret besides the larger size.

**Comment by ghost** [comment] 2015-12-07 21:11
perhaps use Mewtwo2000's old Luigi's Mansion skin for it?

**Comment by bb010g** [comment] 2015-12-09 03:59
This is on the edge of what we're trying to do, but hear me out: I think Ashleyware would be a good Z alt for Wario Land, keeping in theme with the Z older stage pattern in 3.6.1 and Melee Battlefield. ~~I _think_ it's purely cosmetic, but if it's not, could we fix that?~~ (EDIT: I'm a derp. They use this in netplay, so as long as we pull from there, we're fine.)

**Comment by ghost** [comment] 2015-12-09 04:21
Yeah, 3.6 Beta used Ashleyware, if you were wondering. It was a placeholder until 3.6 full came out with Wario Land.

**Comment by bb010g** [comment] 2015-12-09 04:21
They still use it in netplay because it's easier to render.

**Comment by pharoahfawcett** [comment] 2015-12-09 04:53
I'd recommend leaving the stages out. To me it looks like they were tests of some sort, especially the Norfair ones.

Additionally, Ashleyware is a Z stage in my personal build but I don't think it fits the purpose of this build.

**Comment by bb010g** [comment] 2015-12-09 04:55
I'd keep Peach's Castle Melee and vanilla PS2. Those are fun for friendlies.

**Comment by JCOnyx** [comment] 2015-12-09 05:06
If we really want to change up the alts, these would be my recommendations:

Luigi's Mansion - REMOVE Dracula's Castle alt, with Delfino's Secret now a thing we don't need this stage
Norfair - REMOVE 3.02 and 2.6 alts, they aren't necessary and were rebalanced into 3.5 Norfair for a reason
PS2 - Keep PS2 (Brawl) as a secret alt
Bowser's Castle - REMOVE Peach's Castle (Melee) as a secret alt (adding it to another stage)
Dreamland - Change 64 Dreamland to a secret alt and add Green Greens back as the regular alt, following the same pattern as Hyrule Castle's alts.
Wario Land - Add Ashleyware as a secret alt.
Peach's Castle HD - Change Rainbow Cruise to another secret alt (not sure what button to hold, hopefully not X or Y because of stage strikes) and add Peach's Castle (Melee) back as the regular alt

If we are only going to keep the ones in the leaked builds, I'd suggest removing at least Drac's and the Norfair alts.

**Comment by JCOnyx** [comment] 2015-12-09 05:08
But as Pharoah pointed out, I don't see this within the scope of the project to be honest and would rather the new alts (except perhaps PS2 Brawl, I could see that being adding in officially) be removed.

**Comment by bb010g** [comment] 2015-12-09 05:09
The only issue with moving Rainbow Cruise to Peach's Castle HD would be loosing the stage synced music, but Rainbow Cruise (Melee) wouldn't sound that bad on Peach's Castle. But the other changes LGTM; I appreciate the consistency.

**Comment by ghost** [comment] 2015-12-09 05:23
They can have some shared themes on Peach's Castle's slot, as the Slider/Rainbow Cruise theme is loosely associated with all three as it is.

**Comment by bb010g** [comment] 2015-12-21 03:59
This is now the main issue for stage discussion as a whole. Stage suggestions should not involve completely new content until February.

**Comment by JackpotSHUnited** [comment] 2015-12-21 05:31
https://gist.github.com/JackpotSHUnited/c6e01dfe06a6ac45ff5d

Here is a stagelist proposal that I've been planning for my own build. It includes new content, but some parts of it might be useful for this discussion.

**Comment by bb010g** [comment] 2015-12-21 05:40
Relevant stuff from Sandfall:
- [Halberd & FoD stage slot stuff](https://www.reddit.com/r/SSBPM/comments/3kw0i8/amonday_week_43_sandfall/cv1bnbc)
- [Rebalanced Yoshi's Island?](https://www.reddit.com/r/SSBPM/comments/3kw0i8/amonday_week_43_sandfall/cv1bsh9)
- [Kongo Jungle 64 HD](https://www.reddit.com/r/SSBPM/comments/3kw0i8/amonday_week_43_sandfall/cv1i1e4)
- [Luigi's Mansion bug](https://www.reddit.com/r/SSBPM/comments/3kw0i8/amonday_week_43_sandfall/cv2334v)
- [Sandfall's Pokemon Stadium Redux](https://www.reddit.com/r/SSBPM/comments/3thygl/pmdt_what_happened_to_sandfalls_pok%C3%A9mon_stadium/)

**Comment by JackpotSHUnited** [comment] 2015-12-21 05:53
If he was referring to Yoshi's Island N64, it's possible that a rebalanced version would look something like the SD Remix version, which removes the clouds and the top platform. This is also the version of the stage used in the Melee Community Netplay build.

**Comment by bb010g** [comment] 2015-12-21 05:55
He was talking about YI:B, as he says that it's one of his favorite stages. Don't most tourneys ban that because of slopes?

**Comment by JackpotSHUnited** [comment] 2015-12-21 05:58
I don't think we should make any major changes to Yoshi's Island Brawl considering it's already a counterpick in the recommended ruleset. Every tournament I've been to or watched has kept it legal.

**Comment by bb010g** [comment] 2015-12-21 06:05
Maybe as an alt? I don't know; just putting Sandfall's plans out here.

Left some comments on your Gist.

**Comment by bb010g** [comment] 2015-12-21 06:33
[My take on things.](https://gist.github.com/bb010g/87fa0806c421d3bbe123)

**Comment by LoanSPW** [comment] 2015-12-21 20:28
According to Llama Juice (dev of PM), an HD version of Kongo Jungle was planned to be included in ver 4.0, so I was wondering if someone is going to make one for PMCC.
Source: https://www.reddit.com/r/SSBPM/comments/3i3ius/hd_melee_stages_in_the_next_update/
"Does this mean that we're done rehashing old stages? No, of course not. I'm still super excited to see Kongo Jungle HD, and I know you guys are too."

It could look like something like that:
![kongojunglehd](https://cloud.githubusercontent.com/assets/16327543/11940549/b926da3c-a829-11e5-88a4-c77c2e108bf6.png)

Also that same developper said in a topic in Smashboards that Jungle Japes was set to be its alternate stage (the 64ver being put as an hidden alternate stage) and Green Greens was set to be put as an alternate stage for Dreamland HD, due to the team wanting to have all the stages from Brawl coming back (except 3, which are unpopular and hard to play on: Mushroomy Kingdom, 75m and Mario Bros.).

If we follow this statement, that means that Mario Circuit was set to come back!

So what do you think about this?

PS: Just my opinion: I remember that Peach's Castle (Melee) was found as an alt for Bowser's Castle in the files of 3.61. If Mario Circuit comes back, I think it would be better to put PC as an alt for it.

**Comment by LoanSPW** [comment] 2015-12-21 20:36
Also, I said that I was going to open an issue about the "new" leaks, but I can confirm that some elements of it were fake. It was said in the leak that Venus Lighthouse was going to be one of the new stages. However Llama Juice confirmed that the stage was never intended to be in an official PM build.

Other stuff included new costumes and music changes. Some of them I can confirm were true, other were discutable. I will discuss them in another issue right now.

**Comment by ghost** [comment] 2015-12-29 01:19
[Icons.zip](https://github.com/TheOriginalSINe/Project-M-CC/files/74978/Icons.zip)

I propose this stage list. Only thing that is technically new is Jungle Hijinx, which I believe was in a really early Project M release.

I also have the art assets/code ready.

Example: 
![metal cavern - large](https://cloud.githubusercontent.com/assets/16377058/12028133/5364adf6-ada0-11e5-87b9-a14e5f0583a8.png)

Example:
![pokemon stadium 2 - large](https://cloud.githubusercontent.com/assets/16377058/12040173/abfd5b22-ae34-11e5-9cc1-8546d1ee4b21.png)

**Comment by ghost** [comment] 2015-12-29 18:44
Updated my link above. Please look!

**Comment by bb010g** [comment] 2015-12-30 03:13
What's the general consensus on putting in rebalanced stages? What about netplay alts?

**Comment by pharoahfawcett** [comment] 2016-01-03 21:05
i personally am bothered by that... the stage listing should be vanilla 3.61. i dont like it when people force their custom build on others

**Comment by LoanSPW** [comment] 2016-01-23 11:46
For a V.1 release, I think we should keep the 3.61 stage list, as we are unsure of what the PM team was really going to release in 4.0. We could also include some high quality custom content (as long as the stages were made by members of the PM Team)...

My propositions:

-Move Bowser's Castle on Luigi's Mansion slot, Fountain of Dreams on Halberd's and Jungle Japes on Kongo Jungle's. 

That makes Space for three new stages (on Mario Circuit, Jungle Japes and Mario Bros. Slots)

Then on these three slots:

-Mario Circuit slot: obviously, the return of Mario Circuit from Brawl.

-Mario Bros. Slot: A Golden Sun stage. Venus Lighthouse could work.

-Jungle Japes slot: An Advance Wars stage. None exist at the moment, so If nobody's going to create it, we could just go with a second Sonic Stage (there's an awesome Aquarium Park stage already made).

Then the alts:

-Big Blue: SSE Falcon Flyer (the one where you're fighting Meta Ridley) could Be the alt.

-Port Town: Mute City (Melee) as the alt. Mewtwo2000'version is still in the works.

-Saffron City HD: Put "Poke Floats 2" as the alternate stage and move "Saffron City 64" as the hidden alternate stage.

-Spear Pillar: SSE Rayquaza's Lake as an alt. Mewtwo2000 made a revamped version of it, called "Alive Rayquaza's Lake", where Rayquaza makes the effects of Dialga, Palkia, Cresselia. This version is awesome!

**Comment by LoanSPW** [comment] 2016-01-23 11:59
Alts pt. 2:

-Battlefield: Battlefield 64 as the Hidden alternate stage

-Final Destination: Brawl Final Destination as the alternate stage

-Fountain of Dreams: Halberd as the alt.

-Dreamland HD: Green Greens Put as the alt and Dreamland 64 moved as an hidden alternate stage.

-Kongo Jungle (HD?; depends if someone's create It or not): Jungle Japes as the alt (and Kongo Jungle 64 as the Hidden alternate stage if an HD version is created).

-Bowser's Castle: Luigi's Mansion as the alt, Bowser's Castle (legal) as the hidden alternate stage. [Possibly with Blue Lava?]

-Distant Planet: SSE Jungle (from PM 2.5) coming back as an hidden alternate stage.

-WarioLand: AshleyWare coming back as an hidden alternate stage.

-Mario Circuit: Princess Peach's Castle (Melee) coming back as an alternate stage.

-Venus Lighthouse: A legal version as an alternate stage.

This is only a stage list proposition. If you want the links of the stages I'm talking about, I can put them right there! :)

**Comment by LoanSPW** [comment] 2016-01-23 12:02
Also I Forgot...

-Training Room: SSE Midair Stadium could fit as an alt. Just put PM Main Theme instead of the Online Practice Stage music.

These stages proposition are for V.2 of course. And Sorry for the multiple posts...

**Comment by bb010g** [comment] 2016-01-23 19:40
Could you put that in a Gist in the format of the other ones here to make it easier to compare?

**Comment by LoanSPW** [comment] 2016-01-23 19:55
Ok I'll do it! How do I do that?

**Comment by LoanSPW** [comment] 2016-01-23 19:55
*How do I do that?

**Comment by bb010g** [comment] 2016-01-23 19:56
https://gist.github.com/ and look at the other comments for examples. (Also, please edit your comments instead of double posting.)

**Comment by LoanSPW** [comment] 2016-01-23 21:26
Here it is:
https://gist.github.com/anonymous/7a118896f8a40ef7e386/f8109bc063de95ea4b87cfc69d93475eea599c84#file-community-completion-build-stagelist-proposal

**Comment by LoanSPW** [comment] 2016-01-23 21:35
Here it is:
https://gist.github.com/LoanSPW/e9bdc315b0a0bc67eb98#file-cc-build-stagelist-proposal

**Comment by LoanSPW** [comment] 2016-01-23 21:58
EDITED! There are now two versions of my stagelist: the "more-official-looking" one and my "ideal/more complete" one.

V.1: https://gist.github.com/anonymous/bf775853ebceddc347dc#file-cc-build-stagelist-v-1

This one includes 6 new stages compared to 3.6 (3 of them are from Brawl and the 3 others are from earlier versions of PM): Final Destination (Brawl), Mario Circuit, Green Greens, Peach's Castle (Melee), AshleyWare and SSE: Jungle. Also, Legal Bowser's Castle now has blue lava.

V2: https://gist.github.com/LoanSPW/64c37f26d45bd4e9ff00#file-cc-build-stagelist-v-2

This one includes all the stages from V.1, but adds even more (including some custom content made by members of the PM Team).
New stages are: Battlefield 64 HD, Kongo Jungle 64 HD, Mute City (Melee), Venus Lighthouse (and its competitive version), Aquarium Park, Poké Floats 2, SSE: Midair Stadium, SSE: Rayquaza's Lake, SSE: Falcon Flyer.
So, V.2 has 16 more stages than 3.6 (and 10 more than V.1 for a total of 85 stages!).

If we don't find something that the majority like, I think we should stay with v3.61 stagelist however

**Comment by ghost** [comment] 2016-02-01 03:02
@bb010g this seems to erroneously still be open, another dupe-like thing.

**Comment by ithunderHD** [comment] 2016-02-01 03:11
Or we can just use the stage expansion tool for the stages that easier with out having to move stages around

**Comment by ghost** [comment] 2016-02-21 19:47
Okay, lets revive this discussion. What should we do?

**Closed as completed** 2016-07-16 17:52 UTC
Labels: Low Priority, Stages

**Comment by bb010g** [comment] 2016-07-17 22:40
Out of scope.

**Comment by NicBric6** [comment] 2018-11-22 01:51
The download link isn't working, so I was wondering if you could update it

**Comment by chickangamer** [comment] 2018-11-22 01:53
It’s been literally forever since this project was mentioned

**Comment by NicBric6** [comment] 2018-11-22 02:12
I was just gonna try out project m and then I saw this, so I just wanted more content

**Comment by chickangamer** [comment] 2018-11-22 02:17
I understand.Although I should tell you this project is long dead but their
is a project M mod that I can recommend which is Legacy Ce.The only
characters they’re currently missing is Isaac Sami and Lyn.But Lyn is
coming in the next update so that one less character. But if you need more
info and have a discord here is the inv link:
https://discord.gg/SDXxPmU
And if not I can give you a download link myself.

**Comment by NicBric6** [comment] 2018-11-22 02:18
Thanks =D

**Comment by NicBric6** [comment] 2018-11-22 02:20
Where can I find the download at?

**Comment by chickangamer** [comment] 2018-11-22 02:33
Well if your in the discord you can look in the discord channel and find
which ever build suits you

**Comment by NicBric6** [comment] 2018-11-22 02:34
but like where do I find the builds at? Sorry, I don't use discord all too much

**Comment by chickangamer** [comment] 2018-11-22 02:36
Well check general under discussion first and I’ll try to guide you there

**Comment by NicBric6** [comment] 2018-11-22 02:39
okay
