### ISSUE TITLE
ROB has wrong Stock Icons on his Vitural Boy Alt

### ISSUE THREAD

**Issue by SiLLyDJ** [TheOriginalSINe/Project-M-CC#365] opened 2016-02-19 05:25 UTC
http://puu.sh/ndkIH/3940256182.jpg

http://puu.sh/ndkUk/80d7607c4b.jpg

**Comment by SiLLyDJ** [comment] 2016-02-19 05:27
Only does it ingame

**Comment by bb010g** [comment] 2016-02-19 14:28
Duplicate of #193.

**Closed as completed by bb010g** 2016-02-19 14:28 UTC
