### ISSUE TITLE
Menu: New Battle Portraits

### ISSUE THREAD

**Issue by ewmb7701** [TheOriginalSINe/Project-M-CC#16] opened 2015-12-03 20:35 UTC
Multiple Characters do not have their Battle Portraits match up with their new CSPs.

Effected Characters:
Mario
Luigi
Peach
Yoshi
Wario
Captain Falcon
Falco
Link
Toon Link
Meta Knight
King De De de
Samus
Zero Suit Samus
Olimar
Jigglypuff
Mewtwo
Ivysaur
Charizard
Ness
Ike
Sonic

Suggested Fix:
Export all CSPs and painstakingly crop every single one to make a new image, then import them into the Battle Portraits files located at \projectm\pf\info\portrite

**Comment by ghost** [comment] 2015-12-03 23:18
You could talk to SJS, as he makes a lot of CSPs and BPs. He might also have had a hand in making the PM ones.

**Comment by ghost** [comment] 2015-12-04 19:22
Fixed these. Sent you a PM on Reddit.

**Comment by ghost** [comment] 2015-12-04 19:34
New CSP's have a different lighting effect than the older CSP's. This creates a lack of consistent visual style.

2 possible solutions:
1. Find the artist who created the new CSP's and ask him to finish them for the rest of the cast.
2. Roll back the new CSP's to their 3.6 renditions for the sake of visual consistency.

**Comment by ghost** [comment] 2015-12-04 20:01
@Azuran17 I personally think they're fine the way they are but SJS has done CSPs for the rest of the cast in a similar style. However I think that goes beyond a "fix" as some might object to SJS's CSPS and PMDT weren't going to add those specific ones in the first place

**Comment by ewmb7701** [comment] 2015-12-04 20:53
Hmm I think for now we should roll back the CSPs to the 3.6 for the "Release" build. I agree that we shouldn't use SJS's CSPs Anything else will take a very long time to implement, and I'd like to get the release done this weekend. Also I can't seem to find that fix you PM'd me on Reddit. What's your username?

**Comment by ghost** [comment] 2015-12-04 20:59
same as here. check your inbox, it probably got mixed in with your replies. I'll try to find a PM function on here as well

**Comment by ghost** [comment] 2015-12-04 21:02
@TheOriginalSINe good call. I feel like this should be the stance for the rest of the project as well. If something included can't feasibly be finished, it should be rolled back to 3.6.

Also I have a sinking suspicion this project isn't gonna be ready to release in the next two days...maybe 2 months. There is a lot to clean up with Lyn and Knuckles. Lots of animation work that takes a lot of time for a decent animator, which I don't even know if we have.

**Comment by ghost** [comment] 2015-12-04 21:10
All the non-"clone character" issues could be fixed by this weekend, and Knuckles isn't far away from completion.

**Comment by ewmb7701** [comment] 2015-12-04 21:17
Yeah the "Release" Build is just a build that fixes all the issues that aren't new characters I'd like to get released this weekend. Mostly to get some publicity for the project, to attract animators and such. Also I got your battle portrait fixes @pharoahfawcett , they look really good. I'm still debating whether or not it's a good idea to roll them back to 3.6 tho, as @Azuran17 pointed out, it'll be hard to get those CSPs and such from the original creator. However, we could also use SJS's CSPs to fill in the gaps, as they are similar enough to the new ones. Some costumes simply don't have 3.6 pictures as well, like Awakening Roy and the new ZSS skins.

**Comment by ghost** [comment] 2015-12-04 21:22
Creator of the PMDT CSPs is SJS jsyk. I don't think the mix is bad, as the PMDT has always had "mixed" CSPs. Maybe offer the other SJS CSPs if people want unity?

**Comment by ewmb7701** [comment] 2015-12-04 21:38
Hmm. Yes that's true, there has always been mixed versions. I feel that they were working towards having a new CSP set for each character, but that would be up for debate. For now I think that using the new Battle Portraits would be good, and if SJS doesn't want us to use the CSPs, then we can roll them back.

**Comment by ghost** [comment] 2015-12-04 21:48
Did anyone ask SJS if we could use his CSPs? It could be possible that he will be willing to make CSPs for us.

**Comment by ghost** [comment] 2015-12-04 21:51
I have a good feeling PMDT was not going to release a build with half the characters having new style portraits and half having old. We probably got the build as they were halfway through changing everyone's portrait.

For completion and professionalism sake, I still suggest an all or nothing. Either we convince SJS to help and complete all portraits, or we roll back to vanilla.

**Comment by ewmb7701** [comment] 2015-12-04 22:33
The Halloween update was planned for release for Halloween, but was abandoned. However, I agree with the sentiment of "all or nothing". For now we'll revert them to 3.6, but we'll ask SJS if he would like to complete them for us.

**Comment by ghost** [comment] 2015-12-04 23:40
don't ask SJS to complete them... he is PMDT and inherently against the leaks. do a rollback if you want consistency

**Comment by bb010g** [comment] 2015-12-05 01:16
[**@pharoahfawcett**](https://github.com/pharoahfawcett) commented on [Dec 4, 2015, 12:59 PM PST](https://github.com/TheOriginalSINe/Project-M-Dev-Build-Completion/issues/16#issuecomment-162080554):

> I'll try to find a PM function on here as well

GitHub doesn't have private messaging.

[**@pharoahfawcett**](https://github.com/pharoahfawcett) commented on [Dec 4, 2015, 3:40 PM PST](https://github.com/TheOriginalSINe/Project-M-Dev-Build-Completion/issues/16#issuecomment-162111036):

> don't ask SJS to complete them... he is PMDT and inherently against the leaks. do a rollback if you want consistency

I'd be fine with rollback, but he may have also been purged instead of brought under the gag, so it's worth a shot.

**Comment by ghost** [comment] 2015-12-05 02:45
I talked to him, and he respectfully declined. I can search around to find other CSP creators. There was this one guy whose name started with an L that made good quality CSPs, but I have to look for him.

**Comment by ghost** [comment] 2015-12-05 04:06
@JekyllMD that is a step away from restoring PMDTS work and towards a new content mod which isn't the goal of this project

**Comment by bb010g** [comment] 2015-12-05 04:22
Yeah. If we can't keep going with the new CSPs at the same quality, :+1: for revert.

**Comment by ghost** [comment] 2015-12-05 05:22
All I'm trying t do is get quality CSPs back into the game. You were fine if we had SJS help us, even though he would have to make new CSPs. If SJS doesn't want to help us with that, why wouldn't we ask someone else to have a more unified look for the CSPs?

**Comment by ghost** [comment] 2015-12-05 06:16
here's my opinion:
- brawl CSPs are ugly
- unified CSPs are great
- the new CSPs fit well with the Brawl ones
- PM CSPs typically haven't matched well

I see no problem with leaving the CSPs as they are in the dev build.

**Comment by pharoahfawcett** [comment] 2015-12-15 00:43
has this been decided? can it be closed?

**Comment by ghost** [comment] 2015-12-15 00:49
This seems odd to be closed. Isaac and Lyn's CSPs don't even show the correct models in the initial leak, and our Lyn replacement stands out against the Brawl ones. Some new solution has to be made if we want consistency for all CSPs.

**Comment by somealternateaccount** [comment] 2015-12-16 09:36
Needs more discussion about whether or not to update battle portraits to match new character selection portraits, etc, etc.

**Comment by ghost** [comment] 2015-12-16 14:04
I think the most important this is whatever is decided, we ought to strive for a consistent style on the CSS. Even when PMDT added in Roy and Mewtwo, they did their best to emulate the lighting/style of the rest of the casts' portraits.

Two options I see:
- Revert all portraits to 3.6 style and just trying to match that style for Lyn and Knuckles. This would mean all Alt portraits would have a different pose from the default.
- Create new CSPs in SJS's style for all characters who still have default CSPs. Alternate portraits and default portraits could be given the same poses. However this option deviates from PMDT's work more, seems like much more work for us, and introduces many opportunities for arguments over artistic differences.

**Comment by JackpotSHUnited** [comment] 2015-12-16 17:28
I mean SJS's portraits were pretty much considered to be "canon" for Project M even if they weren't actually used until this new build. I don't think anyone would mind if we just used the rest of SJS's portraits from the Brawl Vault.

**Comment by somealternateaccount** [comment] 2015-12-16 17:36
This is kind of backwards, but it feels bad to just steal SJS's work, _especially_ because he is former PMDT. We don't want to imply that our work is supported by the old PMDT, because it is not.

**Comment by JackpotSHUnited** [comment] 2015-12-16 17:49
I mean we kind of already stole Knuckles's taunts from an old PSA.

**Comment by bb010g** [comment] 2015-12-16 17:57
We tried to contact them for approval, but they had disappeared.

**Comment by ghost** [comment] 2016-05-18 18:31
Figure that this should be closed, given the full revert to 3.6 icons being confirmed.

**Closed as completed by ghost** 2016-05-18 18:31 UTC
Labels: User Interface
