### ISSUE TITLE
Knuckles star K.O has no sound.

### ISSUE THREAD

**Issue by leon09090** [TheOriginalSINe/Project-M-CC#280] opened 2015-12-30 07:09 UTC
Whenever you star KO knuckles there is no sound. Also, if you're playing as sonic it plays sonic's star ko sound

**Comment by thesmashking25** [comment] 2016-01-01 22:03
Obviously playing as sonic will produce Sonic's star ko sound.

**Comment by bb010g** [comment] 2016-01-01 22:38
Duplicate of #81.

**Closed as completed by bb010g** 2016-01-01 22:38 UTC
Labels: Audio, Knuckles
