### ISSUE TITLE
Knuckles has Sonic's mouth

### ISSUE THREAD

**Issue by Darquezze** [TheOriginalSINe/Project-M-CC#236] opened 2015-12-19 00:40 UTC
When Knuckles is doing a certain attack, he has sharp teeth while in some moments (getting hit, near the ledge) He has the mouth of Sonic

**Comment by bb010g** [comment] 2015-12-19 02:46
What's the issue here? (Feeling like a duplicate of #228.)

**Comment by Darquezze** [comment] 2015-12-19 02:50
@bb010g kinda similar, Knuckles has different mouths in different moments 
1st  is like #228 with Knuckles sharp teeth
The 2nd is like Sonic teeth, not sharp

**Comment by bb010g** [comment] 2015-12-19 02:51
Could you give examples of the second?

**Comment by Darquezze** [comment] 2015-12-19 02:56
Me being dumb, I don't know how to post pictures on here (I'm using Mobile version)

**Comment by Darquezze** [comment] 2015-12-19 03:04
@bb010g here u go https://plus.google.com/115474315144239483658/posts/VH56TQ1Yvng

**Comment by jgd124** [comment] 2015-12-19 03:48
I mean... Looking at it, it seems pretty intentional. 

Knuckles would look extremely stupid if he had those big, sharp teeth showing in every animation. 

Personally, I think it looks stupid on his side smash, but that's just me.

**Comment by UNOwen3** [comment] 2015-12-19 08:08
Knuckles has 7 different mouths used in different animations. The sharp teeth only appear in the Angry_Mouth one.

Him having no teeth on his surprised face is completely intentional.

**Comment by bb010g** [comment] 2015-12-19 18:25
Toothless mouth is intentional.

**Closed as completed by bb010g** 2015-12-19 18:25 UTC
Labels: Model/Animation, Low Priority, Knuckles
