### ISSUE TITLE
Knuckles: Placeholder Sound Effects

### ISSUE THREAD

**Issue by Karrotkonvoy** [TheOriginalSINe/Project-M-CC#161] opened 2015-12-13 08:17 UTC
Knuckles' dodge roll uses a sound effect from Sonic's up taunt animation. Also, his sound effect for balancing on a ledge is a copy of the one he uses for jumping.

Suggested fix: Use a common dodge roll sound, and find some kind of "woah" clip to use for balancing.

**Comment by pharoahfawcett** [comment] 2015-12-13 22:45
http://www.sounds-resource.com/search/?q=knuckles

**Comment by bb010g** [comment] 2016-01-01 22:39
Duplicate of #81.

**Closed as completed by bb010g** 2016-01-01 22:39 UTC
Labels: Audio, Low Priority, Knuckles
