### ISSUE TITLE
Isaac and Sami Use the Smash Bros series symbol on the victory screen

### ISSUE THREAD

**Issue by PowerpointSmasher** [TheOriginalSINe/Project-M-CC#335] opened 2016-02-02 23:24 UTC
Title

**Comment by bb010g** [comment] 2016-02-03 02:26
Duplicate of #13 & #112.

**Closed as completed by bb010g** 2016-02-03 02:26 UTC

**Comment by PowerpointSmasher** [comment] 2016-02-03 19:38
I look through both threads and both of them don't mention the new series symbols not appearing on the victory screen.
