### ISSUE TITLE
Knuckles: Grounded Spring behaves like Sonic's spring

### ISSUE THREAD

**Issue by Kosyne** [TheOriginalSINe/Project-M-CC#158] opened 2015-12-12 22:22 UTC
When using up-b to leave a spring on the ground, the spring left behind bounces as high as Sonic's spring. In addition, it has no sound effects.

**Comment by ghost** [comment] 2015-12-12 23:19
Don't know if I would consider the height to be an issue. But the missing sound effect is.

Tagging as audio issue.

**Comment by bb010g** [comment] 2015-12-12 23:46
It should be lower for consistency.

**Comment by ghost** [comment] 2015-12-13 01:11
Consistency with what?

EDIT: Nvm just tested, I see what you mean. Spring should send you only as high as it does upon using grounded up B

**Comment by bb010g** [comment] 2016-01-01 22:41
Audio part is duplicate of #81.

**Comment by ghost** [comment] 2016-01-01 23:16
@bb010g This is an issue with Knuckles' spring data in his rel file, AFAIK. Pyotr Luzhin would have to take a look at it.

**Comment by bb010g** [comment] 2016-01-01 23:25
Yeah, the spring height is still possibly a bug.

**Comment by Kosyne** [comment] 2016-01-10 01:01
Confirming that this still occurs on the new Knuckles leak (along with the sound bug), despite changes to the aerial UpB.

**Comment by bb010g** [comment] 2016-03-07 02:07
Leaving as is for now.

**Closed as completed by bb010g** 2016-03-07 02:07 UTC
Labels: Moveset/Hitboxes, Low Priority, Knuckles
