### ISSUE TITLE
Kirby doesn't get an ability from Knuckles.

### ISSUE THREAD

**Issue by JackpotSHUnited** [TheOriginalSINe/Project-M-CC#388] opened 2016-03-17 03:56 UTC
This seems to be the last thing left before Knuckles is complete other than a few animation fixes. Since it's a physical attack, we wouldn't need to create any new articles for the dive attack. It's all a matter of whether we can figure out how to add new Kirby abilities.

**Comment by bb010g** [comment] 2016-03-17 05:00
Duplicate of #118.

**Closed as completed by bb010g** 2016-03-17 05:00 UTC
