### ISSUE TITLE
Lyn standard b animation

### ISSUE THREAD

**Issue by darkralts** [TheOriginalSINe/Project-M-CC#251] opened 2015-12-20 17:37 UTC
The animation of the standard b is static (dont know if thats the right word but) and she looks very akward as pit and link both draw back their arrows as charging and make a charging sound. Lyn just sits there frozen in place until arrow release. I dont know how to ad tags so could someone add: Low Priority, Lyn, animations, and a tag related to movesets and specials. Thanks. :+1: 
[20151220_112826.zip](https://github.com/TheOriginalSINe/Project-M-CC/files/67880/20151220_112826.zip)

**Comment by cobalt-blue** [comment] 2015-12-21 10:47
why low priority? lyn is one of the shorter term goals this build wants to complete, so logically it needs attention.

what we need is the animation redone (it's obviously a placeholder currently), and I suggest to mirror her bow stance and animation from FE7. the attack should charge at the frame that mirrors the sprite highlighted with the red dot below.

![14093](https://cloud.githubusercontent.com/assets/16147993/11929072/a73d10c0-a81f-11e5-8982-8f601dac015f.gif)

**Comment by ghost** [comment] 2015-12-21 13:48
Duplicate of #30 closing

**Closed as completed by ghost** 2015-12-21 13:48 UTC
Labels: Model/Animation, Lyn

**Comment by bb010g** [comment] 2015-12-21 17:26
Whoops, sorry I missed that this was a dup. @cobalt-blue, you may want to repost that in #30.

**Comment by darkralts** [comment] 2015-12-21 17:51
Should i close this then? Sorry im new to github. Just trying to do my best
to help :)

**Comment by bb010g** [comment] 2015-12-21 17:53
The issue has already been closed. (You should have a separate email saying that @Azer-X closed it from about 4 hours ago.)
