### ISSUE TITLE
Knuckles glitch

### ISSUE THREAD

**Issue by Awsoman62** [TheOriginalSINe/Project-M-CC#237] opened 2015-12-19 02:40 UTC
There was a glitch with Knuckles where he started on the right and he Side B, he teleported to the left side of the stage and couldn't use any moves and there were no sounds I also could not hit him so I had to exit the game. It was on Green Hill Zone.

**Comment by bb010g** [comment] 2015-12-19 02:48
Duplicate of #166. Please put any new info there.

**Closed as completed by bb010g** 2015-12-19 02:48 UTC
