### ISSUE TITLE
Include costumes put in the "fake" leak

### ISSUE THREAD

**Issue by LoanSPW** [TheOriginalSINe/Project-M-CC#262] opened 2015-12-21 21:02 UTC
In the "leak" I mentionned in two other posts, on thing in it is confirmed false: the Venus Lighthouse stage, as it was never set to be in PM according to its creator. However, it said things about the music and other stages inclusion completely right. So what about the costumes that leaked?

In the leak, it was mentionned a "Sinbad the Sailor" costume for Knuckles (as he appeared in Sonic and the Secret Rings)
![sinbadthesailor](https://cloud.githubusercontent.com/assets/16327543/11941103/7733cf00-a82d-11e5-9d4e-c92ff22a54df.png)
First, it looks cool, and then, a 3d-like artwork, that I never saw elsewhere, was uploaded to accompagny it.
![sinbadthesailor3d png](https://cloud.githubusercontent.com/assets/16327543/11941119/9f859c54-a82d-11e5-861c-fe28eb6ce32c.jpg)

Then, it was said that an Awakening Lyn costume was set to be included, but no images accompanied it as no work on it began according to the leaker. Here's the original artwork of Awakening Lyn:
![lynawakening](https://cloud.githubusercontent.com/assets/16327543/11941217/45aff124-a82e-11e5-8f10-06bbccedaa95.jpg)

The PED Suit was confirmed as the 10th costume for Samus, with a new costume of ZSS that seems to be inspired of the one in Smash 4:
![txvzcss](https://cloud.githubusercontent.com/assets/16327543/11941209/34804dfe-a82e-11e5-80db-7daee05dfce9.png)

So here's the question: should we include these costumes, or do like nothing happened?

**Comment by ewmb7701** [comment] 2015-12-21 21:20
I think all of those costumes are great, and if they were confirmed to be added at some point, I have no issue with adding them. 

Especially that Zero Mission Justin Bailey. Love that one.

**Comment by Kippy232** [comment] 2015-12-21 22:50
Seconded! I love the concept of the these as potential alts

**Comment by pharoahfawcett** [comment] 2015-12-22 02:09
these are definitely fake, you can reverse image search ZSS and Knuckles

no point in adding any but ZSS as potential alt for PED

**Comment by Tottle** [comment] 2015-12-22 02:49
Nobody said once these were all PMDT artworks, we have all seen most of these, just the visual source material of what they were going to do.

That Sinbad Knuckles model is badass, definitely should be used as the basis for an alternative costume.
.

**Comment by jojmaht** [comment] 2015-12-22 11:16
That's too bad, I would have loved a corrupted ZSS to go with the PED Suit Samus. 
![yc8fhoh](https://cloud.githubusercontent.com/assets/5133452/11953999/156cc786-a8a5-11e5-86bd-91ed73225e8f.jpg)
But then again, outside of project scope and all.
I'm in favor of the Orange Justin Bailey.

**Comment by UltraSyko** [comment] 2015-12-22 11:58
Tbh I love the Venus LightHouse Stage and I think it should be in the CC Build. I think LlamaJuice actually worked for some PM Stages so it's technically PM's vision

**Comment by Kippy232** [comment] 2015-12-22 16:34
@skinnyfoetusboy Corrupted ZSS would go perfectly with PED Suit Samus. I wonder if the 10th ZSS alt is still up for discussion..?

**Comment by ewmb7701** [comment] 2015-12-22 21:10
Actually if this leak is fake, we really shouldn't add any of it to the build.

**Comment by LoanSPW** [comment] 2015-12-22 21:21
Well as of now, we don't really know. 3 months ago, Venus Lighthouse wasn't planned to be added, but maybe the devs changed their minds! I didn't realised that earlier...

**Comment by jgd124** [comment] 2015-12-22 23:37
@LoanSPW Maybe the devs _didn't_ change their minds.

The two shown costumes are concepts that are nice but I don't see them as anything more than unformed scribbles (even if they were real). 

I also recognize the orange csp as a custom SJS Character portrait from about a year ago. 

https://www.dropbox.com/sh/c0bhgwyaqd83zi5/AAAw0zoT20fL1E36jewuidjca/Old%20Set%205?dl=0&preview=bszerosuit5mzm.png

So I don't count that picture as actual "proof" if that's what's being used to prove it.

**Comment by bb010g** [comment] 2015-12-23 00:38
:+1: for Corrupted ZSS along with PED Suit instead of Brawl ZSS. We have to choose an alt to go there, so why not choose the one that pairs well?

**Comment by Tottle** [comment] 2015-12-23 02:45
If Corrupted ZSS was less of a cliche evil costume, then I think it could be cool. The ghostly pale skin and garish blue face paint being too much to resemble the PMDT's level of professionalism. It looks like a cheap mod with all that. I would suggest using @Pr0gram's head in its place with perhaps very light touches of corruption from the beginning of the game outside the Zero Suit itself.

As to alternative costumes, I'd say even if this is fake (as it is looking) Secret Rings Knuckles is still an obvious choice. And Awakening Lyn is an obvious choice too.

**Comment by pharoahfawcett** [comment] 2015-12-23 03:46
@TheOriginalSINe yeah, that's what i said. you can reverse image search the knuckles model. this leak is confirmed fake. llamajuice has said venus lighthouse wouldn't have made it in.

**Comment by Kippy232** [comment] 2015-12-23 05:02
@bb010g I could not agree more

@Tottle Regardless of how cliche it is, it is canon and at least fits the PED suit. However, it does appear quite odd in the above screenshot and may actually look even stranger in-game. I'm sure someone (@Rage17 or @Pr0gram maybe?) could manage to make it work without looking as awful as it does above.

**Comment by Tottle** [comment] 2015-12-23 05:10
That's what I mean. While the concept itself may have a source in canon, the implementation of it is pretty bad. The visual representation of being corrupted so early in this case shouldn't look like a user of the dark side in a Star Wars game.

It should also be noted: she is only around 10% corrupted in the Prime 3 PED suit this costume is based off. So she should have at worst a very light blue vein on the right side of her face, not all that.

Look how you can't even see any facial corruption in the first pic, right after she gets the PED suit.   http://metroid.wikia.com/wiki/Phazon?file=CorruptedFace.jpg

**Comment by jojmaht** [comment] 2015-12-23 07:11
I was not saying _this_ particular unfinished BrawlVault mod, of course. I was just posting the picture as a reference. Like, a few lines across her face (but not so much that she ends up looking like an emogoth shopping at Hot Topic) and blue, phazon-y eyes would be good.

@Tottle Her Zero-Suit corruption state wouldn't necessarily need to perfectly reflect the amount of corruption shown by her PED suit.

**Comment by cobalt-blue** [comment] 2015-12-24 03:06
there is probably some truth to some of the supposed costumes here, I'd say that Lyn was definitely supposed to get her awakening outfit, much like Roy.

**Comment by pharoahfawcett** [comment] 2015-12-24 04:03
why not ask any former PMDT member if there's truth behind the leak? it's seemingly fake, but if a PMDT member confirms or denies, it's settled whether they should be added

**Comment by somealternateaccount** [comment] 2015-12-27 04:53
This seems really out of the scope of the project.

**Comment by Kippy232** [comment] 2015-12-29 03:35
Maybe at a later date, once this project is all but finished, we could consider adding reasonable alts to Knuckles, Issac, Lyn, and (the ever popular) Sami. For now this seems unnecessary.

**Comment by bb010g** [comment] 2015-12-29 05:30
Let's table this until February. I know we know that the PMDT was planning to fill all the alt slots, but there's enough newness here I think it qualifies. Closing and moving future discussion over to #277.

**Closed as completed by bb010g** 2015-12-29 05:30 UTC
Labels: Costumes, User Interface, Model/Animation, Low Priority, Lyn, Knuckles, Tabled

**Comment by mamimamis** [comment] 2015-12-29 19:50
I would like the Knuckles from Sonic and the Secret Rings and Awakening Lyn because they only have different colors for their alt costumes
