### ISSUE TITLE
Lyn: D-Smash Animation 

### ISSUE THREAD

**Issue by JCOnyx** [TheOriginalSINe/Project-M-CC#52] opened 2015-12-06 04:45 UTC
The animation of her D-Smash has her sword go super far into the Z axis.  This causes the move to miss on occasion when it otherwise looks like it would hit.  Smash is a 3D game, but I'm assuming this was an oversight.

I've had this happen when D-Smashing an opponent in a prone state, their knockdown state, and attempting to recover.

**Comment by ghost** [comment] 2015-12-10 03:21
Confirmed. Both the animation and the hitboxes are too deep into the Z axis to hit on many characters. Additionally, the hitboxes don't match the sword animation.

Suggested Fix: Rotate Lyn about 10-15 degrees clockwise during the animation. Also adjust the two hitboxes to better follow her sword movement.

**Comment by aFracture** [comment] 2015-12-15 07:21
I'd also like to add to this Issue (instead of making a new one): a bit more about what @Azuran17 mentioned with the hitboxes. 

When they get adjusted for the Z-axis problems I think their X- and Y-axes should be looked at as well. They should be moved slightly away from her body and should be remade to cover the entire length of her sword. Right now, they do not cover the last 10% or so of her sword. This is most observable when she is on a platform. If she down-smashes, you can often see the tip of the blade go directly into an opponent, but they will not be hit because of this.

I suggest that the current 2 hitboxes be changed to 3 (slightly smaller) boxes, which will cover the entire length of the sword, and be moved outward from her body a little, so that they are centered on the blade.

**Comment by ghost** [comment] 2015-12-15 11:13
So we have a WIP fix for this already in the build AFAIK, but i'll wait for more feedback before closing this.

**Comment by ghost** [comment] 2015-12-15 13:20
Yea JCOnyx is working on it. Also, the tip missing through platforms that you are observing is caused by the Z axis depth issue.

**Closed as completed** 2016-07-16 17:34 UTC
Labels: Moveset/Hitboxes, Low Priority, Lyn
