### ISSUE TITLE
Knuckles: Getup attack missing Audio

### ISSUE THREAD

**Issue by ghost** [TheOriginalSINe/Project-M-CC#148] opened 2015-12-11 18:40 UTC
Knuckles's getup attack plays no audio or sound effect.

Suggested fix: Copy over the getup attack sound from a different character with a similar getup attack animation

**Comment by bb010g** [comment] 2016-01-01 22:41
Duplicate of #81.

**Closed as completed by bb010g** 2016-01-01 22:41 UTC
Labels: Audio, Low Priority, Knuckles
