### ISSUE TITLE
Ness Vs Lyn Crashes Game Frequently

### ISSUE THREAD

**Issue by ghost** [TheOriginalSINe/Project-M-CC#74] opened 2015-12-06 21:17 UTC
When Ness and Lyn vs, the game crashes most of the time. If Ness uses his PK Fire or something, it crashes vsing her.

**Comment by Eltrion** [comment] 2015-12-06 23:54
Could not reproduce. Could you provide a more detailed description. Lyn seems to interact with Ness's moves normally

**Comment by ghost** [comment] 2015-12-07 00:43
Sure, let me start up PM and I'll let you know if it still happens. If it does, I'll tell you how it happens.

**Comment by ghost** [comment] 2015-12-07 00:50
Oh and when you copy the files to the SD Card, do you put the codest files in the codes folder?

**Comment by Eltrion** [comment] 2015-12-07 00:52
Just copied the codes and ProjectM folders from the git, then played a few rounds as Ness against a Lyn bot.

**Comment by ghost** [comment] 2015-12-07 00:53
So don't put the text codest files in the codes folder?

**Comment by Eltrion** [comment] 2015-12-07 00:54
I just copied the whole git.
Ness vs Lyn works fine.

**Comment by ghost** [comment] 2015-12-07 00:54
How do you correctly install this?

**Comment by Eltrion** [comment] 2015-12-07 00:55
Just copy the Codes folder and the Project M folder to the root of your SD card. You'll need your own PM Launcher though.

**Comment by bb010g** [comment] 2015-12-07 00:56
You should merge the `codes` folder and the `RSB?01` section of `gameconfig.txt` (or just copy if it's the only patched game you're using) with your SD card, and replace the `projectm` folder.

**Comment by ghost** [comment] 2015-12-07 00:56
So only copy the codes folder, the gameconfig.txt, and the projectm folder?

**Comment by ghost** [comment] 2015-12-07 00:59
Is that what you guys are saying?

**Comment by Hellraz0r** [comment] 2015-12-07 15:55
Get a clean SD card. No files on it. Hit the download as zip button on the github for this. Extract the folder in the zip. Put the contents of that folder on an SD card. You're done.

**Comment by ewmb7701** [comment] 2015-12-07 19:01
Going to close this, as it seems like it was a one time problem.

**Closed as completed by ewmb7701** 2015-12-07 19:01 UTC
