### ISSUE TITLE
Spot dodging

### ISSUE THREAD

**Issue by meta-neo-omega-ridley** [TheOriginalSINe/Project-M-CC#206] opened 2015-12-17 00:54 UTC
Sword goes through Lyn in spot dodging/side-stepping.

![spot dodging](https://cloud.githubusercontent.com/assets/16313695/11858328/a721443e-a42e-11e5-992a-939e36eb467d.PNG)

**Comment by ghost** [comment] 2015-12-17 01:59
This is a duplicate of #106 closing

**Closed as completed by ghost** 2015-12-17 01:59 UTC
