### ISSUE TITLE
3.61 Bug Fixes

### ISSUE THREAD

**Issue by ghost** [TheOriginalSINe/Project-M-CC#101] opened 2015-12-08 20:34 UTC
Now that we have them(here: https://dl.dropboxusercontent.com/u/143448524/3.61%20Changelist.zip ), will we use any of it no that the exact changes have been confirmed?

**Comment by ewmb7701** [comment] 2015-12-08 20:36
Well there was talk of just going ahead and bringing everything up to 3.61. Here's what I said in Gitter: "in the Discord chat, we were discussing the idea of changing back to being based off of 3.61, on the grounds that the tournament standard is 3.6 anyway, and that this build probably wouldn't be accepted anyway. There's not a lot of point to preserving a meta if it's not going to matter anyway, and the changes are so small."

Assuming we don't do that, then we should probably put the bug fixes into our build.

**Comment by JackpotSHUnited** [comment] 2015-12-08 21:02
I personally think that if the PMDT had a changelog ready for 3.61, then the changes made in that version should be considered the "final" version of Project M, even if it wasn't released.

**Comment by ghost** [comment] 2015-12-08 21:07
I do as well.

**Comment by ghost** [comment] 2015-12-08 21:14
Did they have a changelog ready? EDIT: oh dang

**Comment by ghost** [comment] 2015-12-08 21:19
The zip of screenshots of the changelog is the first post here.

**Comment by ghost** [comment] 2015-12-08 21:21
One of the biggest advantages of basing off of 3.6 that I saw: players with this build would still basically be playing the tournament version of the game, but with Knuckles and Lyn "DLC". POTENTIALLY this could, one day, be acceptable in tournaments (as a TO myself, I wouldn't have a problem letting them be legal if after a sufficient amount of time passed and they were determined not to be bugged or broken)

If we were to base this off of 3.61, players would have to adapt to playing two different versions of the game if they wanted to have this build but also play at tournaments.

**Comment by JackpotSHUnited** [comment] 2015-12-08 21:23
If Knuckles and Lyn are present on the character select screen, I have no doubt that any TO will automatically be suspicious of the build. I say everything in that changelog ought to be implemented because otherwise we have to pick out which ones are necessary bugfixes and that could be a controversial jar of caterpillars we probably don't want to open.

**Comment by ghost** [comment] 2015-12-08 21:26
@JackpotSHUnited I definitely think that we can use the files to fix all bugs such as for Yoshi and Bowser. But stuff like moves being reworked for characters like Pit and Roy are balance changes that I don't think should be implemented.

EDIT: You know what. Whatever. I think TO's letting Lyn and Knuckles in tournaments is a pipe dream and included all the changes won't change that much.

**Comment by JackpotSHUnited** [comment] 2015-12-08 21:27
"Due to the nature of this small update, we did not include any balance changes this time around."

**Comment by ghost** [comment] 2015-12-08 21:29
@JackpotSHUnited just look at the changes. Changing Roy's bair, for example, is not a bugfix but a balance change. It doesn't matter if they said they didn't include balance changes, if it walks like a duck, looks like a duck, and quacks like a duck...

But anyways. I think having the changelist and actually knowing what's in our dev build makes me more comfortable with the idea of basing this build off of 3.61

**Comment by JackpotSHUnited** [comment] 2015-12-08 21:31
Honestly most of the actual balance changes on the list are listed as things that were supposed to be in 3.6, but were accidentally left out. And everything else is fairly minor and I doubt it will have any major impact on the meta.

**Comment by ghost** [comment] 2015-12-08 21:35
@JackpotSHUnited you'd be surprised. And you'd probably be even more surprised at how passionate players can be about minor changes to their character and their perceived impact :panda_face:

**Comment by JackpotSHUnited** [comment] 2015-12-08 21:36
(It was in that moment that I experienced a flashback to the day Fox finally had his Shine nerfed.)

(But then I remember the salt and just whisper "lol m2k" to myself.)

**Comment by oXMugetsuoXo** [comment] 2015-12-08 21:37
Staying 3.6 imo is the best way to keep the community from splitting. Having just 3.6 with +2 characters is still 3.6. Having 3.61 which introduces slight character changes is no longer 3.6. This is a turn i would not like to see the project go. I believe bug fixes should be the only thing taken from 3.61

**Comment by ghost** [comment] 2015-12-08 21:49
Ok, seeing as our goal was to squash as many bugs as possible, in a perfect world we would have implemented most of the 3.61 changes already even if we were basing off of 3.6.

If we were to base the build off of 3.61 instead of 3.6, here are the additional changes that would be included:
- Charizard roll going 5 units further
- Ivysaur Forward Tilt Rework, synthesis no longer dealing damage, and jabs+fsmash being clankable
- Kirby has specials changed for Mewtwo Roy Ganon and Ivy. Also armor removed on startup of Down B
- Link Up Smash Buffed
- Lucas Nair, bair, up b and down b altered (properties changed to 3.02 looks like buffs)
- Marth walljump changed
- Pit Up Smash changed (buffed?)
- Roy bair changed and buffed. Walljump changed
- Yoshi's neutral B changed

This seems like a fair amount of extra.

**Comment by JackpotSHUnited** [comment] 2015-12-08 21:50
Would the Link and Pit up smash changes really count as buffs? The wording in the changelog implies that making them link together "properly" is how they were supposed to work in the first place.

**Comment by ghost** [comment] 2015-12-08 21:51
@JackpotSHUnited but these are things we wouldn't have changed ourselves as they weren't considered bugs. They were just considered "bad" moves. They also make the move better, so yea I'd consider them buffs.

**Comment by JackpotSHUnited** [comment] 2015-12-08 22:04
Wait a second, since when does Marth have a wall jump?

**Comment by JCOnyx** [comment] 2015-12-08 22:44
From a wall tech I'm assuming.

**Comment by JackpotSHUnited** [comment] 2015-12-08 22:45
@Rage17 Do you have a source for that changelist by the way?

**Comment by jgd124** [comment] 2015-12-08 22:47
@JackpotSHUnited It's the first link, or are you asking if the changes in the images are confirmed as correct?

**Comment by JackpotSHUnited** [comment] 2015-12-08 22:48
Just want to know where those images came from. Y'know, to verify that they're legitimate.

**Comment by ewmb7701** [comment] 2015-12-08 22:55
http://boards.4chan.org/v/thread/319440761/project-m-news

This thread. I'm skeptical myself. However, pretty much all of these are confirmed changes. And since we're only pulling from the movesets, it really shouldn't matter what exactly they have. I'm trying to verify that they're legit right now.

**Comment by jgd124** [comment] 2015-12-08 23:33
Welp, if this changelog is correct, then it's truly a shame that _this_ wasn't the final release. It would have been pretty solid.

From an objective standpoint, however, this puts the project at a crossroads:

If we implement all characters to 3.61,  the changes made to Marth, Roy, Link, Yoshi, Ivysaur, Lucas, Pit, and Wario will actually affect people who will want to play this build privately and continue to play Project M Gold publicly. 

I know that this build will never be the tournament standard, considering the hard-line stance that I've been seeing from the community leaders, but if 3.CC chooses to incorporate the balance changes of 3.61, beyond the bugfixes, then this build will in some ways be actually rejecting the 3.6 meta, forever standing as a testament to what the game's meta COULD HAVE been.

On the other hand, these changes are fantastic and I don't see them surviving anywhere else but this build. 

My vote is with having the 3.61 version implemented for all characters.

**Comment by JackpotSHUnited** [comment] 2015-12-08 23:38
The way I see it, the goal of Project M is to have a balanced cast. Project M 3.61 is without a doubt more balanced than 3.6, and now that there IS no development team calling the shots, it's up to the community to decide which build correlates with the team's goals. And that build is the unreleased 3.61.

**Comment by jgd124** [comment] 2015-12-08 23:46
@JackpotSHUnited According to the mission statement, one of the goals is still "To preserve the 3.6 meta".

I'm not against implementing 3.61, I'm just asking if the team does or does not want to preserve the 3.6 meta within this build.

Because, although the changes are small, implementing 3.61 no longer preserves the meta of its predecessor.

**Comment by ArtfulHobbes** [comment] 2015-12-08 23:56
"For this update we have been focusing hard to squash as many bugs in 3.6 as we could. Due to the nature of this small update, we did not include any balncing changes this time around. With just bugs and aesthetics, this changelist will look quite a lot smaller than our other ones." - 3.61 Changelist

If we take this changelist for fact, then all of 3.61 really is just a bugfix.

**Comment by ghost** [comment] 2015-12-08 23:57
There were at least a few mentions in the 3.61 changelist that some things in it were left out of 3.6 by mistake, also.

**Comment by jgd124** [comment] 2015-12-09 00:11
@Rage17 @ArtfulHobbes  I know. And sadly, we will probably never see those bugs and mistakes rectified in any official capacity (again, mostly due to the hard-line stance that community leaders have taken.) The mistakes are now parts of the characters and now, therefore, the meta. 

I'm starting to agree with others that said if we truly wanted to "preserve the meta of 3.6" in this build then we probably would make no real attempts to fix Link's chaingrab or Yoshi's shield. 

3.61 is objectively the better, more complete version, but it doesn't preserve the meta of 3.6. 

Of course there's the issue of pulling the trigger on this change cementing the rift between those "staying behind" (3.6) and those "moving forward" (3.CC), but it seems that that issue has already been solved.

The rift is already there and idea of this project has already been demonized.

So I say we just go with 3.61 and tweak our mission to be "a preservation of the intended 3.61 design."

**Comment by ghost** [comment] 2015-12-09 00:14
I agree with @jgd124 here. People already give us crap for wanting to fix anything. Why not fix it all?

**Comment by ewmb7701** [comment] 2015-12-09 00:14
Yeah, I've been looking over the changelist and a lot of it can be considered a bugfix as Uie was saying. Also as @jgd124 just pointed out, even bug fixes can be considered a change to the meta. And those that want to keep the 3.6 versions of characters can just copy and paste in the fighter files anyway. It's not like this build will ever be tournament standard, so we might as well just fix everything as @Rage17 put it.

**Comment by jgd124** [comment] 2015-12-09 00:17
@TheOriginalSINe @Rage17 

I mean, "fix everything" within reason though. I'm not sure if making any balance changes to any characters beyond minimal ones to the newcomers would be warranted.

But I'm sure you two already know that.

**Comment by ewmb7701** [comment] 2015-12-09 00:18
@jgd124 Oh yeah of course. I never wanted to do any balances other than what was leaked or in 3.6 and newcomers.

**Comment by gooeywreck408** [comment] 2015-12-09 00:18
I know my opinion wont matter much since i have no experience in brawl modding but,i think that since project m is supposed to be about balancing and if you can confirm that change log to be true there's no reason not to add the 3.61 changes including the minor balancing ones.but if you really want to preserve the  3.6meta can you just make two branches, 3.6 with bug fixes and then 3.61. I know you don't want to divide up the community anymore than it already is but I believe that to be the best idea.thank you guys for all your work I really appreciate being able to play as knuckles and Lynn.

**Comment by ironFe93** [comment] 2015-12-09 01:05
The real 3.61 seems to have been leaked lads. Just a heads up
http://boards.4chan.org/v/thread/319468021

**Comment by jgd124** [comment] 2015-12-09 02:26
@cotarola93 Yes. We are aware. (Guys, I'm assuming this is the same as "The Halloween Build".) It was previously leaked a couple days ago. Thank you for the heads up though.

**Comment by AJ3450** [comment] 2015-12-09 02:32
what the fuck? Is this the same as the Halloween build? Can anyone test it?

**Comment by ironFe93** [comment] 2015-12-09 02:37
This isn't the halloween build, but a new leak, supposedly was to be released sometime later this month. The guys over at the discord chat already seem to be aware of this one though.

**Comment by AJ3450** [comment] 2015-12-09 02:40
Well this complicates things.

**Comment by bb010g** [comment] 2015-12-09 03:18
That's the same build as the old Halloween one. Same Mega link & everything.

**Comment by ewmb7701** [comment] 2015-12-09 03:24
New build uses 3.6.1 as a base. Closing.

**Closed as completed by ewmb7701** 2015-12-09 03:24 UTC

**Comment by ghost** [comment] 2015-12-09 03:27
Haven't weighed in on this in a bit.

The 3.6.1 build contains a lot of bug fixes that we would have needed to do ourselves had we based the project on 3.6.

However, it also contains a number of changes that we would not have implemented as they air on the side of balance changes rather than bug fixes (I provided a list in a previous post)

Given this though, now that we know exactly what is in it, 3.6.1 is objectively a better build than 3.6. Why not use it if it will both improve the quality of the project and also save us a shitton of time trying to fix bugs that have already been fixed.

I am for using it as a base.

EDIT: Aaaannnd SINe beat me to it

**Comment by bb010g** [comment] 2015-12-09 03:38
The things I would say infringe with 3.6 meta & balance would be Charizard (glide resets & roll distance, although roll distance was supposed to be normalized in 3.6, Zard players will still be expecting those), Ivysaur (KB & KBG changes), Kirby's stone startup armor, Link (maybe usmash), Lucas (nair, bair), Marth (walljump), Pit (maybe usmash, glide timings), & Roy (bair, walljump). Those are a bit far for bugfixes IMHO.
