### ISSUE TITLE
Sami Solo Mode Crash

### ISSUE THREAD

**Issue by icecapman10** [TheOriginalSINe/Project-M-CC#304] opened 2016-01-09 23:39 UTC
title

**Comment by Kippy232** [comment] 2016-01-10 00:05
Can you describe the exact requirements for the crash?

**Comment by icecapman10** [comment] 2016-01-10 00:07
On the character select in a solo mode, when I highlight Sami, the game crashes.

**Comment by Kippy232** [comment] 2016-01-10 00:12
Did you make sure you downloaded the most recent version?

Are you loading Wifi Set, or the Full Set? Are you using Dolphin or Wii? Wii U?

**Comment by icecapman10** [comment] 2016-01-10 00:14
I have the most recent version (yesterday). I have the Dev Resources on the card. I'm using a Wii U.

**Comment by Kippy232** [comment] 2016-01-10 00:15
Okay, just asking for posterity. I'll test it out when I get a chance

**Comment by icecapman10** [comment] 2016-01-10 00:15
Thanks

**Comment by Tac24** [comment] 2016-01-11 08:13
sami wouldn't even work for me... reverted to old codeset

**Comment by GunBlazer** [comment] 2016-02-18 21:51
Duplicate of #321

**Comment by PowerpointSmasher** [comment] 2016-02-18 22:05
@Hemijack Lol how could this be a duplicate when it came first

**Comment by GunBlazer** [comment] 2016-02-22 05:58
...that's what sleep deprivation does to you.

**Closed as completed** 2016-07-16 17:13 UTC
Labels: Low Priority, Sami
