### ISSUE TITLE
Include features mentioned in a past leak

### ISSUE THREAD

**Issue by PKSmashOmega** [TheOriginalSINe/Project-M-CC#267] opened 2015-12-22 20:37 UTC
Alongside the Knuckles and Lyn leak video, the same leaker revealed more on 4chan.
https://mega.nz/#F!URBzURqb!z-g4icCSSCP73_17cutDhw this folder has pics of the posts.

**Features in this leak that are CONFIRMED (leak was pre-3.5) -**
- Knuckles, Lyn, Isaac and Sami
- N64 Mode
- Bowser's Castle
- Espio, Charmy and Vector alt colors for Knuckles (+1 point for this leak)

and a bunch of other stuff (minor details on stages/costumes for ZSS, Ganon).

**New features (not in any official build) -**
- New CSS
- Ridley as a playable character (planned at one point)
- Metal Knuckles (Sonic Advance?) skin for Knuckles

**Comment by cimpyhigh** [comment] 2015-12-22 20:45
This feels fake... I don't remember Ridley ever being confirmed, that would've been a huge sweep across the community. Just my two cents, haven't had a chance to look at pics. Feels like a fanboy's ideal build attempting to trick the community into adding. Just me though :)

**Comment by Darquezze** [comment] 2015-12-22 21:43
Ridley seems totally fake but Knuckles does deserve alternate costumes kinda like Sonic with his Shadow and Silver Skins (I don't count Tails because there's nothing special about it unless someone adds 2 long tails to that costume)

**Comment by PKSmashOmega** [comment] 2015-12-22 22:09
I should have made it more clear. When these were posted (late 2014), Ridley was only planned (according to the leak), and could have easily been replaced or removed. Since so much of the leak was later added to PM (or found in the dev build) I think the leak is legit.

**Comment by jgd124** [comment] 2015-12-22 23:33
This seems fake. But even if we assume that it is real, it has been ONE FULL YEAR since then and the PMDT's design sensibilities have changed since then. 

If the leak is true (which it isn't), then it is a snapshot of what they were thinking _at the time_. We have no guarantee that some of the more drastic changes (new CSS/Ridley) were even going to be added in so I don't think they should be required for the build.

**Comment by bb010g** [comment] 2015-12-23 00:36
The PMDT said before that while they appreciated some of the higher quality community work (e.g. Venus Lighthouse, Sky Sanctuary Zone, Ridley / Waluigi), they wouldn't be in PM because they wanted their own work to go in. That makes this seem pretty fake to me.

**Comment by archedmaid** [comment] 2015-12-23 01:34
Correct me if I'm wrong, but I think wizz said in his ama that they were planning Ridley, but he was either to big or so small he looked dumb.  Then they just canned the idea.

**Comment by cobalt-blue** [comment] 2015-12-23 04:52
this is actually completely legit. ridley, however, was - keyword - a POTENTIAL character. as mentioned above, this fell through because issues with making him feasible. at the time of the actual disbandment i believe that several people claimed dark samus had taken the slot, but we'll never know really.

**Comment by Kippy232** [comment] 2015-12-23 04:57
I'm just praying for the day that it a Dark Samus build is leaked and my dreams of adding Dark Samus to the roster will finally be fulfilled... but, far more likely, neither Ridley, nor DS will ever find their way into Project M in any legitimate form, aside from PSAs.

**Comment by Darquezze** [comment] 2015-12-23 04:58
Pichu was shown in an April Fools video. So I guess he's a character u can use but he could have been a joke like Parasect (if u were going too I'll rather use Brawl Minus 4.0's version of Pichu.) Really high chances it won't happen since its out of the projects goals

**Comment by Darquezze** [comment] 2015-12-23 04:58
@Kippy232 Costume

**Comment by somealternateaccount** [comment] 2015-12-23 20:53
Closing this - not only were most of these things not planned anyway, but this is out of scope.

**Closed as completed by somealternateaccount** 2015-12-23 20:53 UTC
