### ISSUE TITLE
PED Suit Samus

### ISSUE THREAD

**Issue by ewmb7701** [TheOriginalSINe/Project-M-CC#3] opened 2015-12-03 05:01 UTC
PED Suit Samus is not displayed on the CSS screen.
The CSS slot mapping needs to be changed.
This could possibly be accomplished using Mewtwo2000's cBliss tool for Project M 3.6.

**Comment by ghost** [comment] 2015-12-03 23:22
I thought he used his cBliss tool already so up to 10 character slots can be used

**Comment by jgd124** [comment] 2015-12-06 06:27
Here's a question: are we _positive_ that the PED suit was intended for release? I mean it makes sense, seeing as most of the implemented costumes were made by Nanobuds and the PED suit was also created by Nanobuds... 

But this particular skin was created and released on brawlvault back in 2014 (http://forums.kc-mm.com/Gallery/BrawlView.php?Number=204449). 

Are we positive that it wasn't just a test character or something put in the files on a whim?

I haven't checked to see if there are any distinct visual changes between the two, can anyone confirm any differences?

Otherwise, I'm pretty sure this costume is just a old one that a dev was toying with and was something that was not for sure going to be included in the final release.

**Comment by ewmb7701** [comment] 2015-12-06 06:30
Well it has a CSP and a RSP. I also don't think a dev toying with it would get pushed to a shared build like that.

**Comment by jgd124** [comment] 2015-12-06 06:32
@TheOriginalSINe Whoops. I must have missed that. My b. I guess it's just another Nano costume that they were going to implement eventually.

**Comment by Karrotkonvoy** [comment] 2015-12-16 11:44
So I was playing around with PM's "Masquerade Costumes" code, trying to make sense of it, and I found a way to make PED Samus load with just a few byte changes. Just search for "06586248" and replace the next few lines:

06586248 00000018
02000103 00010404
03020805 09070A08
07060609 0C000000

Every 4 bit string loads a different costume with the first byte defining team color and the second telling which "FitfighterXX.pac" to load. All I did was move "0C00" over, add 4 to the amount of bytes to include, and put in "0609" to load "FitSamus09.pac" as a non-team color. This would seem consistent enough to other characters maxed out to ten slots.

PED is perfectly playable and even loads the CSP, and stock icons just fine. There's a few problems though. I noticed the stock icons on the results screen and the SSS are incorrect. Also, her final smash will just hang if you try and transform at the end. Despite the issues being minor, I'd say we should leave it out of this particular build for consistency reasons since the CSP is different and it has no matching Zero Suit. 

I'd be happy to commit the changes if the consensus concludes otherwise.

**Comment by bb010g** [comment] 2015-12-16 17:05
Put it in a PR.

**Comment by bb010g** [comment] 2015-12-29 05:31
Closing due to this being the result of Nanobuds messing around and by request of Nanobuds to not use his Vault models without expressed permission. Any future new PED Suit alts should be put up for discussion first at #277.

**Closed as completed by bb010g** 2015-12-29 05:31 UTC
Labels: Costumes, User Interface

**Comment by Kippy232** [comment] 2015-12-29 07:10
So very, very close, but oh-so far away. :/
