### ISSUE TITLE
Lyn: F-Smash Leg Clipping

### ISSUE THREAD

**Issue by ghost** [TheOriginalSINe/Project-M-CC#121] opened 2015-12-10 03:24 UTC
Lyn has a large amount of upper leg and dress clipping during the entirety of this move.

Suggested Fix: Clean up dress and underware animations.

**Comment by somealternateaccount** [comment] 2015-12-16 09:11
Closing as a dupe of #65.

**Closed as completed by somealternateaccount** 2015-12-16 09:11 UTC
Labels: Model/Animation, Low Priority, Lyn
