### ISSUE TITLE
Samus Costume

### ISSUE THREAD

**Issue by meta-neo-omega-ridley** [TheOriginalSINe/Project-M-CC#224] opened 2015-12-18 02:36 UTC
Samus had the PED suit (corruption suit) in her fighter folder, but it has not yet been implemented into the game. A code for extra costume slot for Samus or something similar would fix this.

**Comment by ghost** [comment] 2015-12-18 02:39
There is a pull request that implements it.Also, an issue already exists that covers this. This issue thread should be closed.

**Comment by somealternateaccount** [comment] 2015-12-18 11:21
Closing of duplicate of #3, #209, etc.

**Closed as completed by somealternateaccount** 2015-12-18 11:21 UTC
