### ISSUE TITLE
Sonic: Battle Portrait Inconsistency

### ISSUE THREAD

**Issue by MrGameCrazy** [TheOriginalSINe/Project-M-CC#194] opened 2015-12-16 08:57 UTC
Sonic's BPs (besides his regular and Jet Set Radio costume) are inconsistent with the CSPs.

Here's the 2 that are correct:

Regular Sonic:
![00000000-64](https://cloud.githubusercontent.com/assets/16161703/11836356/d5a28e10-a39f-11e5-8533-3206db2b5c82.png)
![00000000-63](https://cloud.githubusercontent.com/assets/16161703/11836354/d59c9be0-a39f-11e5-9c45-f932968d9853.png)

Jet Set Radio Sonic: 
![00000000-77](https://cloud.githubusercontent.com/assets/16161703/11836390/11eb3692-a3a0-11e5-9b89-5aee75519664.png)
![00000000-76](https://cloud.githubusercontent.com/assets/16161703/11836391/11eb5d2a-a3a0-11e5-9440-cc2ccc96677a.png)

The rest of the BPs like the one below are inconsistent with their respective CSPs.

Shadow Sonic: 
![00000000-71](https://cloud.githubusercontent.com/assets/16161703/11836477/9d68ca40-a3a0-11e5-8bf4-92500d5c01fd.png)
![00000000-70](https://cloud.githubusercontent.com/assets/16161703/11836478/9d6c746a-a3a0-11e5-950b-27714c7975ca.png)

**Comment by somealternateaccount** [comment] 2015-12-16 09:16
I think this occurs with other characters. Each character and each costume should be checked, perhaps in Brawlbox, to see which portraits are used. Ideally, battle portraits should match character selection portraits.

**Comment by MrGameCrazy** [comment] 2015-12-16 09:22
Alright. I don't know where exactly I would find the CSPs and BPs in
Brawlbox, though.

**Comment by somealternateaccount** [comment] 2015-12-16 09:34
This appears to be a duplicate of #16. Closing for now. Future discussion should take place there.

**Closed as completed by somealternateaccount** 2015-12-16 09:34 UTC
Labels: Costumes, User Interface
