### ISSUE TITLE
Issac: Neutral B bug in Training

### ISSUE THREAD

**Issue by bubbabeck51** [TheOriginalSINe/Project-M-CC#306] opened 2016-01-11 02:36 UTC
I was in training mode as Issac and was trying out his moves against a computer, but when I changed the computer from stop to attack, Issac's neutral b caused him to teleport around the stage and when I turned the computer back to stop it worked again.

**Comment by ghost** [comment] 2016-02-01 02:29
@bb010g Another duplicate issue.

**Comment by bb010g** [comment] 2016-02-01 06:59
Duplicate of #159.

**Closed as completed by bb010g** 2016-02-01 06:59 UTC
Labels: Moveset/Hitboxes, Low Priority, Isaac
