### ISSUE TITLE
Kunckles extra customes and sami extra customes crash the game on the CSS

### ISSUE THREAD

**Issue by Tac24** [TheOriginalSINe/Project-M-CC#374] opened 2016-02-22 07:08 UTC
common5.pac  is going to have to be edited pretty soon, whats causing the costume crash?

I don't support putting a largely unfinished sami in the CSS- issac passes the cut cause he has all the BP data and CSS but sami needs more work

**Comment by Kippy232** [comment] 2016-02-22 20:38
I'm not seeing the issue here. Please describe your issue.

**Comment by Kippy232** [comment] 2016-02-22 20:40
Also, duplicate of https://github.com/Project-M-CC/Project-M-CC/issues/304. This should be closed.

**Comment by DestinyHiro** [comment] 2016-02-25 01:12
Actually Sami just needs her Stock Icons for Solo mode which is an easy fix, I'm not really the best with Github so I'll tell the others on Discord

**Comment by PowerpointSmasher** [comment] 2016-02-25 02:04
IMO Sami is more complete than Isaac.

**Comment by vinegar97** [comment] 2016-03-07 05:14
If anybody can confirm the CSS crash, please post about it here, otherwise this shoud be closed pretty soon.

**Comment by bb010g** [comment] 2016-03-07 05:21
Closing, can reopen on issue.

**Closed as completed by bb010g** 2016-03-07 05:21 UTC
