### ISSUE TITLE
Thoughts on Adding Recolors to Alternate Costumes

### ISSUE THREAD

**Issue by vinegar97** [TheOriginalSINe/Project-M-CC#222] opened 2015-12-17 23:40 UTC
After @Karrotkonvoy successfully added PED suit samus using PMs official costume code, i tought about doing the same with other characters, as some costumes were just begging for recolors or were actually planned to have recolors eventually before PMs cancellation.

this issue is for discussing the potential of adding alt costumes, so what do you guys think ?, should only recolors be added ?, do you support adding all-new alts ?

**Comment by ewmb7701** [comment] 2015-12-17 23:48
Only alternates that we can confirm were planned should be added.

**Comment by Kippy232** [comment] 2015-12-18 01:14
I couldn't agree more with TheOriginalSINe. Alternate costumes should be limited, and additions are moreso custom content.

**Comment by ghost** [comment] 2015-12-18 01:25
+1 @TheOriginalSINe

**Comment by vinegar97** [comment] 2015-12-18 02:18
what about recolors ? some costumes were planned to be given team colors (like two other hats for jiggs that use headband physics, which some PMDT member suggested were may's bow and jigglypuff's blue bow from melee,and awakening roy was planned to have recolors), and some were obviously going to get them (like OoT zelda and sheik, and maybe retro captain falcon).

**Comment by Grangach** [comment] 2015-12-18 02:34
I would be for a more liberal approach to added content, I think it's fair to assume that alternate colors for alt costumes would have been implemented at some point in development had pm continued. I think the same goes for new alt costumes, as long as they are quality and within the spirit of pm I would like to see more added.

**Comment by ghost** [comment] 2015-12-18 02:41
Yeah, they should have some sort of precedence(like a costume theme that a character has) or at least have dome hints suggesting that they were planned.

**Comment by vinegar97** [comment] 2015-12-18 02:56
for anyone in doubt, here are some screenshots:
![awkeningroy](https://cloud.githubusercontent.com/assets/16244042/11888169/e807932c-a54b-11e5-9cee-e82733cb56b0.PNG)
![headbandjiggs](https://cloud.githubusercontent.com/assets/16244042/11888168/e80526f0-a54b-11e5-93b4-de0f1024fda5.PNG)

**Comment by ghost** [comment] 2015-12-18 02:57
@vinegar97 I can toy with getting a blue bow and May's hat on Jiggs, if we like.

**Comment by JackpotSHUnited** [comment] 2015-12-18 03:04
I also recall Nano stating that Beta Knight would probably get alt colors if they couldn't think of any better alt costume ideas for him. Might as well give him a blue and green option for the butterfly wings.

**Comment by vinegar97** [comment] 2015-12-18 03:08
@Rage17 yeah that would be great if it's not to much trouble!

**Comment by UltraSyko** [comment] 2015-12-18 03:46
Codex's Armored Charizard and Retro Pit Recolors. If someone can contact him for permission that would be dandy
Also a Jet Set Future Skin for Sonic would be cool 
![00000000-289](https://cloud.githubusercontent.com/assets/16283463/11888855/78998206-a510-11e5-8d09-cb011dff58ab.png)

**Comment by ghost** [comment] 2015-12-18 04:06
I think there is still a large amount of confusion about the goals and scope of the project.

In Scope: Finishing leaked content. Knuckles, Lyn, Issac, Sami (iffy on the last two due to lack of content we have as a base to work off of) 64 mode. Anything specifically relating to these that falls under making them "complete" IE metal costumes for 64 mode models, planned alts for the new characters, final smashes.

Out of scope/for your own personal builds: Anything else. New stages, New characters, new modes, menu redesigns, alts we have no leaked evidence of, costume modifications. Balance changes (at least for a long time). Things that PMDT SAID they wanted to do eventually, but no files/codes to base that work on were leaked.

**Comment by vinegar97** [comment] 2015-12-18 04:35
Fair enough, guess i got a little ambitious, sorry for the inconvenience.

**Comment by somealternateaccount** [comment] 2015-12-18 11:23
Closing for now as these concerns look to be out of scope. @Azer-X, do you think something should be added to the README to address the scope of the project?

**Closed as completed by somealternateaccount** 2015-12-18 11:23 UTC

**Comment by Kippy232** [comment] 2015-12-18 12:45
"What This Build is NOT: This build is not aiming to be the new "tournament standard". It is simply a group of modders coming together with the common goal of finishing Project M the way it was intended to be. It is also not a new custom content mod. The goal is to stay as true to PMDT's design as possible. This build is neither a place to add tons of new characters nor rebalance the entire game. Perhaps in the future Isaac can be completed, but as of right now, the focus is on finishing what is almost done!" (from README.md)

@somealternateaccount There already is a place in the readme about the scope of the project; "It is also not a new custom content mod."
