### ISSUE TITLE
Issac Melee Battlefield Glitch

### ISSUE THREAD

**Issue by icecapman10** [TheOriginalSINe/Project-M-CC#390] opened 2016-03-22 01:41 UTC
When using Issac"s neutral special in Melee's Battlefield, the screen glitches out with green static in random spots.

**Comment by ghost** [comment] 2016-03-22 10:08
This glitch has been known for quite some time. Although the actual color looks different in some places, the cause is the same(an error with his coding for diagonal slopes in the move). Closing.

**Closed as completed by ghost** 2016-03-22 10:08 UTC
